fix(ci): add release verify step
Signed-off-by: skuethe <56306041+skuethe@users.noreply.github.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -37,6 +37,11 @@ jobs:
           fi
 
       - name: Verify Release Version
+        run: |
+          if [[ "$(gh release view $RELEASE_VERSION 2>&1)" != "release not found" ]]; then
+            echo "ERROR: release already exists"
+            exit 1
+          fi
 
       - name: Checkout Self
         uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
